name: Deploy to App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ecp-walking-challenge
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Update db password
        run: sed -i 's/<db_password>/${{ secrets.DB_PASSWORD }}/' src/main/resources/application.properties

      - name: Update strava client id
        run: sed -i 's/<strava_client_id>/${{ secrets.STRAVA_CLIENT_ID }}/' src/main/resources/application.properties

      - name: Update strava client secret
        run: sed -i 's/<strava_client_secret>/${{ secrets.STRAVA_CLIENT_SECRET }}/' src/main/resources/application.properties

      - name: Deploy to App Engine
        run: |
          mvn clean package appengine:deploy