name: Deploy to App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: trackdogs
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Replace environment variables in app.yaml
        run: |
          sed -i 's|${STRAVA_CLIENT_ID}|'"${{ secrets.STRAVA_CLIENT_ID }}"'|g' app.yaml
          sed -i 's|${STRAVA_CLIENT_SECRET}|'"${{ secrets.STRAVA_CLIENT_SECRET }}"'|g' app.yaml
          sed -i 's|${DB_PASSWORD}|'"${{ secrets.DB_PASSWORD }}"'|g' app.yaml

      - name: Deploy to App Engine
        run: |
          mvn clean package appengine:deploy
